<template>
  <main
    py4
    min-w-screen-md
    max-w-screen-xl
    mx-auto
    text-neutral-600
    dark:text-light-800
  >
    <h1>🚀 说明</h1>
    <h2>👨🏻‍💻 作者</h2>
    <p>
      Chuck, 数据科学专业大二在校生，坐标九州通衢郑州，目标<span
        font-medium
        text-neutral-800
        animate-pulse
        dark:text-light-800
        >字节</span
      >!
    </p>
    <p>一颗绿到不能再绿的韭菜，却总想着一夜暴富。</p>
    <p>一个天天总想躺平的新时代青年。</p>
    <p>
      哦对了，<span
        font-medium
        text-neutral-800
        animate-pulse
        dark:text-light-800
        >性别男，爱好女。</span
      >
    </p>
    <p>联系方式在下面。</p>
    <p>其他就没有了。</p>
    <h2>🐳 数据</h2>
    <p>
      部分图片数据来自于一个叫
      <a
        href="https://www.baidu.com/"
        target="_blank"
        text-teal-500
        no-underline
        transition
        hover:font-medium
        >百度</a
      >
      的地方。
    </p>
    <p>
      热量数据和部分图片数据来自于一个叫
      <a
        href="https://www.boohee.com/"
        target="_blank"
        text-teal-500
        no-underline
        transition
        hover:font-medium
        >薄荷健康</a
      >
      的地方。
    </p>
    <p>本项目仅仅只是用于完成一个叫 Web 的选修课的作业。</p>
    <p>
      Okay, so 它遵循
      <a
        href="https://baike.baidu.com/item/MIT%E8%AE%B8%E5%8F%AF%E8%AF%81/6671281?fr=aladdin"
        target="_blank"
        text-teal-500
        no-underline
        transition
        hover:font-medium
        >MIT</a
      >
      协议，你可以拿去随便搞，下面有地址，记得给我一个小星星!
    </p>
    <h2>🔧 技术</h2>
    <p>
      用了一个尤姓男子写的一个叫
      <a
        href="https://github.com/vuejs/vue"
        target="_blank"
        text-teal-500
        no-underline
        transition
        hover:font-medium
        >Vue3</a
      >
      的框架。
    </p>
    <p>
      用了一个尤姓男子写的一个叫
      <a
        href="https://github.com/vitejs/vite"
        target="_black"
        text-teal-500
        no-underline
        transition
        hover:font-medium
        >Vite</a
      >
      的打包工具。
    </p>
    <p>
      用了一个叫托尼写的一个叫
      <a
        href="https://github.com/unocss/unocss"
        target="_blank"
        text-teal-500
        no-underline
        transition
        hover:font-medium
        >Unocss</a
      >
      的 Pure CSS 库。
    </p>
    <p>
      用了一个不知道叫什么写的一个叫
      <a
        href="https://github.com/microsoft/TypeScript"
        target="_blank"
        text-teal-500
        no-underline
        transition
        hover:font-medium
      >
        TypeScript
      </a>
      的语言开发。
    </p>
    <p>
      上面是吹🐂🍺的，只有
      <a
        href="https://github.com/unocss/unocss"
        target="_blank"
        text-teal-500
        no-underline
        transition
        hover:font-medium
        >Unocss</a
      >
      用的多了一点
    </p>
    <h2>📮 联系</h2>
    <p>微信: Chuck2302</p>
    <p>邮箱: chuckgao68686@gmail.com</p>
    <h2>💪🏻 最后</h2>
    <p>
      本项目完全<a
        href="https://github.com/cccchuck/must-healthy"
        target="_blank"
        text-teal-500
        no-underline
        transition
        hover:font-medium
        >开源</a
      >，不要白嫖，至少给我个星星，如果实在不愿意给，那我也没办法了，你就白嫖吧！
    </p>
  </main>
</template>
